/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-08-01 09:52:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DTHView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("   background-color: #f4f4f4;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    \r\n");
      out.write("    align-items: center;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding:0 100px 0 100px;\r\n");
      out.write("  max-width: 100%;\r\n");
      out.write("  margin: 30px auto;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("	\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  border-bottom: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav a img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center; /* This centers the list items vertically */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav li {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  margin: 0 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("  color: #298AC2;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-btn{\r\n");
      out.write("	\r\n");
      out.write("  background-color: rgb(255, 0, 0);\r\n");
      out.write("  color: white;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".container1 {\r\n");
      out.write("    \r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.5);\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: rgb(245, 248, 250);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write(".form-container {\r\n");
      out.write("    width: 60%;\r\n");
      out.write("}\r\n");
      out.write(".header {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("input, select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    margin-bottom: 13px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("/* button {\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    background-color: rgb(238, 202, 222);\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("} */\r\n");
      out.write("button, .payment input[type=\"submit\"] {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    background-color: rgb(68, 85, 247);\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("button:hover, .payment input[type=\"submit\"]:hover {\r\n");
      out.write("    background-color: rgb(50, 70, 190);\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("button:active, .payment input[type=\"submit\"]:active {\r\n");
      out.write("    background-color: rgb(35, 55, 150);\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("    width: 35%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<nav>\r\n");
      out.write("      <a href=\"DashboardView.jsp\"><img src=\"./images/logo.png\" alt=\"logo\" /></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"DashboardView.jsp\">Dashboard</a></li>\r\n");
      out.write("        <li><a href=\"ProfileView.jsp\">Profile</a></li>\r\n");
      out.write("        <li><a class=\"logout-btn\" href=\"login.jsp\">Log Out</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container1\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"form-container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1>DTH Recharge</h1>\r\n");
      out.write("            ");

					String errorMessage = (String) request.getAttribute("errorMessage");
					if (errorMessage != null) {
					
      out.write("\r\n");
      out.write("			<p style=\"color: red; font-size: 25px; text-align: center;\">");
      out.print(errorMessage);
      out.write("</p>\r\n");
      out.write("			");

					}
					
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("		<form action=\"DTHController\">\r\n");
      out.write("		<div class=\"DTH-ope\">\r\n");
      out.write("			<label for=\"option\">Select DTH Operator: </label>\r\n");
      out.write("			<select name=\"operator\" id=\"sub\" required>\r\n");
      out.write("		            <option value=\"Airtel Digital Tv\">Airtel Digital TV</option>\r\n");
      out.write("		            <option value=\"TataSky\">TataSky</option>\r\n");
      out.write("		            <option value=\"D2h\">D2h</option>\r\n");
      out.write("		            <option value=\"Dish TV\">Dish TV</option>\r\n");
      out.write("		        </select>\r\n");
      out.write("	     </div>\r\n");
      out.write("	     <div class=\"cons-no\">\r\n");
      out.write("	        <input type=\"text\" name=\"consumerNo\" placeholder=\"Enter Consumer Number\" required maxlength=\"10\" pattern=\"\\d{10}\"\r\n");
      out.write("							title=\"Account number must be 10 digits\"/>\r\n");
      out.write("	        <input type=\"number\" name=\"amt\" placeholder=\"Enter Amount\" required min=\"50\" step=\"0.01\"/>\r\n");
      out.write("	     </div>\r\n");
      out.write("	     <div class=\"payment\">\r\n");
      out.write("	        <input type=\"submit\" value=\"payment\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<img src=\"./images/dthtv.svg\" alt=\"dth recharge svg\">\r\n");
      out.write("</div>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
